[package]
name = "rust_postgres_app"
version = "0.1.0"
edition = "2024"

[dependencies]

tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
axum = { version = "0.8.9", features = ["macros"] }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
bcrypt = "0.19.3"
diesel = { version = "2.2.0", features = ["postgres", "r2d2", "chrono"] }
r2d2 = "0.8"
jsonwebtoken = { version = "11", default-features = false, features = ["rust_crypto"] }
chrono = { version = "0.4.45", features = ["serde"] }
tower = "0.5.3"
